//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAEncryptionTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<RSAParameters xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <Exponent>AQAB</Exponent>
  <Modulus>vADZhTXL8W11/6UTq6WbfVT5qNgZ9WvDAjgiatsUNzqeYdjB2gIKyXzOCMf8m7fY2QIm7bM2VSGRiP62Zza1LMKJQsywL1HHOfs5aXi5T/dkfYhzJZCicO8C5CZRqkZ+36uQ634uLismQ8rsPUuWeLciGLDHhQH9rlmWk1WMfDexaM4wzbYKEKTv+VpNWAiEXh/CNAWatETPLREv+L4GAAJhm4CvplIO9JlQTvQX+PLxnwTsDeQJ8gF2jCUeZMg8eEn+ADw7EsqZbTbnQgWbPDUr4rCtmByGbWude9dCIagBbonplMwh1+glW+FrTOmXwX5BYt8Dj66txGJHLNqR1Q==</Modulus>
</RSAParameters>")]
        public string PublicKeyString {
            get {
                return ((string)(this["PublicKeyString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<RSAParameters xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <E" +
            "xponent>AQAB</Exponent>\r\n  <Modulus>vADZhTXL8W11/6UTq6WbfVT5qNgZ9WvDAjgiatsUNzqe" +
            "YdjB2gIKyXzOCMf8m7fY2QIm7bM2VSGRiP62Zza1LMKJQsywL1HHOfs5aXi5T/dkfYhzJZCicO8C5CZR" +
            "qkZ+36uQ634uLismQ8rsPUuWeLciGLDHhQH9rlmWk1WMfDexaM4wzbYKEKTv+VpNWAiEXh/CNAWatETP" +
            "LREv+L4GAAJhm4CvplIO9JlQTvQX+PLxnwTsDeQJ8gF2jCUeZMg8eEn+ADw7EsqZbTbnQgWbPDUr4rCt" +
            "mByGbWude9dCIagBbonplMwh1+glW+FrTOmXwX5BYt8Dj66txGJHLNqR1Q==</Modulus>\r\n  <P>/+n" +
            "JWCLAeMXpvfY52O7Rz/KLxvCmFcoxeyhRevX2kSI6en22we2WnkrObUZ7x5ooGq9UhsDxRWTK9h0n4k7" +
            "aLMsTYTAZQVEnGo68JXyPlIqealBp9ZmzlII6mPUYL7w3xuNYvOT7mkNFvST0MS3Sd4x2rg4nW9nLyGJ" +
            "yW44jXos=</P>\r\n  <Q>vBErJdvjdt8gxUfyCuSuV65jfzqi37uQRQA/Z2fntPgqyQVtv3AekJzblyVJ" +
            "zXDOe4aTvznSuHB+Ju5hdO8exdDCkw1nXNNjtcYobKrSoYjv+wUaERW5EQ+rZ5E0WzRV+P0JjgZcnrYQ" +
            "CVj75u0r0a8K74f7jACSymHwWU+BPR8=</Q>\r\n  <DP>PzVEONOkjG/9sqCtWwppoh37LjDkJL+jBxNH" +
            "RMKZmvFEVlrUmAORzxkU8WKWUg+eVjD2BK6FKSmjA7Th1AC73JJv//I8WqirquCUUgH5CKxQQlwIP9Qt" +
            "ycF8rajjx26KrEIc+dLo3go9oGEPO1JhCIwWCBmQ2RvrPFwseLabv88=</DP>\r\n  <DQ>i9q4m47JuLx" +
            "1QkAeXrtwawPkOdkBBiAVSTrF67/5Lzrdll/THWnjUOdU5TF1kLEy2+lYNfxqF36QUaM0FiE8YR69k12" +
            "EYCNTIvoZVbYyrK2IyMMif1IILgfZD0uMA8cHqAGD+XoBpoT9p/XkXfZBf80L9NTK23IRty7d7YySL0E" +
            "=</DQ>\r\n  <InverseQ>atLLJCpCopjbg96sSR74QopCLQqQ9f0BJhROCuEJH2RbJjdn5Ep6lQ5S7x28" +
            "Gyq9FjXUuzTjAHqHbwYhvgZ/RMJjD/Fu8O1yc3OyYrcCdpY0eDOHBPEnpGphDh8oFAZ/+jKnBgrfwUNT" +
            "g2xkhgiG6DBdmeBV+zWjfrdipUdEAe0=</InverseQ>\r\n  <D>gHD8KvwT9z9XTG6VP8GGt1ukrWvmYD" +
            "tdIVkEeohuCUVtC2AxICYhBILVqD4pIKG77pZ/zgmP5x1l9ng+WcmQgaHucMqy28E9ISm3kY0+3Zkg+H" +
            "qOYG2t7QX9ra1YQcKjz1/BRIISPsyP+eTa/Q11IcfL7Z5o0UAI9mKSctoRfpLGuGPwu3OcxULdYgxVXo" +
            "xi/4XuV3G6UEqNqf+WBWc0DUUIWJAxtr4me+/Ios8V+E1ejjNaatqMK9rumuTSbHtV9Nz6BiZzEnpVgt" +
            "5M8kQLSniWUcDdzz7JmnBwSXiZq1xKyTncNdzQja7mTS8gLYybOwLdTXR+YaL2r0sFxEQTiQ==</D>\r\n" +
            "</RSAParameters>")]
        public string PrivateKeyString {
            get {
                return ((string)(this["PrivateKeyString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mypubkey.pem")]
        public string PublicPEMFile {
            get {
                return ((string)(this["PublicPEMFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mykey.pem")]
        public string PrivatePEMFile {
            get {
                return ((string)(this["PrivatePEMFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mykey.pfx")]
        public string PrivatePFXFile {
            get {
                return ((string)(this["PrivatePFXFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mycert.crt")]
        public string PublicCRTFile {
            get {
                return ((string)(this["PublicCRTFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lKQUlIOEFtKzVoWmxoT" +
            "UEwR0NTcUdTSWIzRFFFQkN3VUFNRFl4RERBS0JnTlYKQkFNTUEwTnZlREVtTUNRR0NTcUdTSWIzRFFFS" +
            "kFSWVhaV05vWVc1QVkyRnNiR1JsYzJsbmJpNWpiMjB1WVhVdwpIaGNOTVRZd05ESXlNREV5TURVMFdoY" +
            "05Nall3TkRJd01ERXlNRFUwV2pBMk1Rd3dDZ1lEVlFRRERBTkRiM2d4CkpqQWtCZ2txaGtpRzl3MEJDU" +
            "UVXRjJWamFHRnVRR05oYkd4a1pYTnBaMjR1WTI5dExtRjFNSUlCSWpBTkJna3EKaGtpRzl3MEJBUUVGQ" +
            "UFPQ0FROEFNSUlCQ2dLQ0FRRUFyWkRZVjhuTXBISnpnVk1zckppY2NOSUFpU2tMMUtCRAovWnJOa1hkN" +
            "01lVDVDcXphWnlnRmRCRkpGdGZXcFJaQUxlS3BnYzl3SmlNMVBGTDNOR0R3VUIwdmQvbTAxanZmCmRKR" +
            "nMvajZnb3NPNnlCUEdrREhZUXBNUEduc3VnZ2g4R0xTZEd0ZzdhMmc4SDNOTTVZMCtiOVlaVXBncEdQT" +
            "mkKZEZEaGRib2hHOEFtTCt5L3RwWno1TGtvNDFzbkxUbE1mRGs0U05PTjgwb2pJZlh2YUduYVRCMmNQb" +
            "HAwQ2tRVwpRR2NMVXQxWnRxL3VWOWJTdndSMVZlYTdWbi9DQjhjSnlPQVpCMCtpUVdzV0UzWC9WRU54W" +
            "khCZFFIbTVDa01zClVzMU5Za0dKMENHMmExbGlLSlpUTDU1UXErYjVCb0hyY3EybDMvY09ya253Yk4wS" +
            "VF4WWV2d0lEQVFBQm8xQXcKVGpBZEJnTlZIUTRFRmdRVStiTUxKWmdHTzE0eE1QVWZTRTVWa2tnMXIvM" +
            "HdId1lEVlIwakJCZ3dGb0FVK2JNTApKWmdHTzE0eE1QVWZTRTVWa2tnMXIvMHdEQVlEVlIwVEJBVXdBd" +
            "0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFWZ1RSSWVIUUIySzU5VlhvN2hvampwNithRE1rR" +
            "lpCS0lsUXBjZEdkQzdNd3czbHpsMlFRQnJJZzhTcjYKMHdUQ2tFR3BmbEVyb1VwSnZ6QWhOTFJQNzd4T" +
            "0wwd2NOWXZDTUMwcUNhSmFPWkE4YTVTWmJ2MUp1VjdaQU5wagpEOFlGZ2I3VjY4dVkwT3F6VFRkMXYxb" +
            "nBQTE1wVWZKNE5iVW5GbnF2M2c5UWpETkw3bWFrb0VXNXd5WUxTK1E2CkNlUVIvcFd2T2pqOXp1ZUFTW" +
            "EhFM3YvMGRYZll0RXlkWENuT0pVZW8yTEFPSGxkU1FNZm1UeitsdEE1WjZkT2YKcDRaaDd2dE5rUm91e" +
            "UdLQlcxN21FRzlIckEvdWs0NHhJTDFPUHNDM01qSWNjaEpRcCtyTHFURkpCNWJneHlPTgpoL0Z5Smp5c" +
            "np2RURyc09IVzBlTjJZVktVZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K\r\n")]
        public string PublicCRTString {
            get {
                return ((string)(this["PublicCRTString"]));
            }
        }
    }
}
